language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# before script run flake8
# E731 : lambda expression
before_script: flake8 . --ignore E731
# command to run tests
script: py.test
